---
# This playbook play all post common installation for all servers

- hosts: all
  sudo: True

  tasks:
    - name : Update apt cache
      apt  : 
         update_cache=yes

    - name : apt upgrade
      apt : 
         upgrade=yes

    - name : apt dist
      apt : 
         upgrade=dist

    - name: Change hostname
      hostname: 
         name=web01

    - name: install ntp
      apt:  
         pkg=ntp
         state=present
